"""
Complete end-to-end test flow:
1. Test document ingestion (hash creation)
2. Test chunk creation
3. Test RAG retrieval
"""

import sys
import json
import hashlib
from pathlib import Path
from datetime import datetime, timezone


def test_document_ingestion():
    """Test document ingestion with the Duolingo PDF."""
    pdf_path = Path("docs/Q3FY25 Duolingo 9-30-25 Shareholder Letter Final.pdf")
    
    if not pdf_path.exists():
        print(f"❌ PDF not found at {pdf_path}")
        return None
    
    print(f"✓ Found PDF: {pdf_path}")
    print(f"  File size: {pdf_path.stat().st_size / 1024:.2f} KB")
    
    # Create hash
    pdf_bytes = pdf_path.read_bytes()
    sha256_hash = hashlib.sha256(pdf_bytes).hexdigest()
    
    document_record = {
        "document_id": "duolingo-q3-fy25",
        "company_id": "duolingo",
        "version": "v1",
        "sha256": sha256_hash,
        "source_url": "https://investor.duolingo.com/news-releases",
        "created_at": datetime.now(timezone.utc).isoformat(),
    }
    
    print(f"\n📄 Document Ingestion Result:")
    print(f"  Document ID: {document_record['document_id']}")
    print(f"  Company: {document_record['company_id']}")
    print(f"  SHA256: {sha256_hash}")
    print(f"  Version: {document_record['version']}")
    
    return document_record, pdf_bytes


def test_chunk_creation(pdf_bytes: bytes, document_id: str):
    """Test chunk creation from PDF."""
    print(f"\n📦 Testing Chunk Creation:")
    
    try:
        import pymupdf
    except ImportError:
        print("  ⚠️  PyMuPDF not installed, installing...")
        import subprocess
        subprocess.check_call([sys.executable, "-m", "pip", "install", "pymupdf", "-q"])
        import pymupdf
    
    # Extract text and create chunks
    doc = pymupdf.open(stream=pdf_bytes, filetype="pdf")
    total_pages = len(doc)
    print(f"  Total pages: {total_pages}")
    
    chunks = []
    for page_num in range(total_pages):
        page = doc[page_num]
        text = page.get_text()
        
        # Create chunk record
        chunk = {
            "chunk_id": f"{document_id}-page-{page_num + 1}",
            "document_id": document_id,
            "page_number": page_num + 1,
            "content": text.strip()[:2000],  # Limit content for testing
            "embedding": None,  # Would be generated by OpenAI
            "created_at": datetime.now(timezone.utc).isoformat(),
        }
        chunks.append(chunk)
    
    doc.close()
    
    print(f"  Created {len(chunks)} chunks")
    print(f"  Sample chunk (page 1):")
    if chunks:
        print(f"    Content preview: {chunks[0]['content'][:100]}...")
    
    return chunks


def test_rag_setup(chunks: list, document_record: dict):
    """Test RAG setup and retrieval."""
    print(f"\n🔍 Testing RAG Setup:")
    
    # Simulate a sample claim
    test_claims = [
        "Duolingo reported strong user growth in Q3 2025",
        "Duolingo achieved profitability in Q3",
        "Duolingo expanded to new markets",
    ]
    
    print(f"  Sample test claims:")
    for i, claim in enumerate(test_claims, 1):
        print(f"    {i}. {claim}")
    
    # Simulate retrieval (would use embeddings in real scenario)
    print(f"\n  Retrieval simulation:")
    print(f"    Document ID: {document_record['document_id']}")
    print(f"    Company: {document_record['company_id']}")
    print(f"    Chunks available for search: {len(chunks)}")
    
    return {
        "status": "ready",
        "document_id": document_record["document_id"],
        "chunks_count": len(chunks),
        "test_claims": test_claims,
    }


def main():
    """Run all tests."""
    print("=" * 60)
    print("FINTECH CHECK AI - Complete Flow Test")
    print("=" * 60)
    
    # Step 1: Document Ingestion
    result = test_document_ingestion()
    if not result:
        print("\n❌ Document ingestion failed")
        return 1
    
    document_record, pdf_bytes = result
    
    # Step 2: Chunk Creation
    chunks = test_chunk_creation(pdf_bytes, document_record["document_id"])
    if not chunks:
        print("\n❌ Chunk creation failed")
        return 1
    
    # Step 3: RAG Setup
    rag_setup = test_rag_setup(chunks, document_record)
    
    # Summary
    print("\n" + "=" * 60)
    print("✅ All tests passed!")
    print("=" * 60)
    print(f"\nSummary:")
    print(f"  Document created with hash: {document_record['sha256'][:16]}...")
    print(f"  Total chunks: {len(chunks)}")
    print(f"  RAG system ready: {rag_setup['status']}")
    print(f"\nNext steps:")
    print(f"  1. Deploy document-ingestion Tower app")
    print(f"  2. Deploy chunk-storage Tower app")
    print(f"  3. Run RAG verification on sample claims")
    
    return 0


if __name__ == "__main__":
    sys.exit(main())
